[package]
name = "gangway"
version = "0.1.1"
edition = "2024"
readme = "README.md"
description = "It's like playing telephone — but with one person, repeatedly."
license = "Apache-2.0"
repository = "https://github.com/terranesoftware/gangway"
keywords = ["ipc", "daemon", "tokio", "request-response"]
categories = ["network-programming", "asynchronous", "concurrency", "os"]

[dependencies]
bitcode = "0.6.9"
futures-util = { version = "0.3.34", features = ["sink"] }
interprocess = { version = "2.4.4", features = ["tokio"] }
tokio = { version = "1.53.1", features = ["macros", "rt", "sync"] }
tokio-util = { version = "0.7.19", features = ["codec"] }
tracing = "0.1.44"
