[package]
name = "gangway"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
bitcode = "0.6.9"
futures-util = { version = "0.3.34", features = ["sink"] }
interprocess = { version = "2.4.4", features = ["tokio"] }
tokio = "1.53.1"
tokio-util = { version = "0.7.19", features = ["codec"] }
tracing = "0.1.44"
